[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_app = "4dZNUEgxrEzYByv7hYkuNrpVYc1hE588jjSz6PE2iWct"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thehesoyam/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
